site_name: Data Replication in context of Kafka and Event Streams
repo_url: https://github.com/jbcodeforce/kp-data-replication.git
nav:
  - Introduction: index.md
  - Environment provisioning:
      - Run local kafka cluster with docker compose: dc-local.md
      - Strimzi Kafka 2.4 Provisioning on Openshift: provisioning.md
      - Mirror Maker 2 Provisioning: mm2-provisioning.md
  - Replication Scenarios:
    - Replication from local to Event Streams: local-to-es.md
    - Replication from Event Streams to local : es-to-local.md
    - From Event Streams on OpenShift to Event Streams on Cloud : es-prem-to-es.md
  - Best practices:
    - Kafka Summary: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/readme
    - Consumer practices: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/consumers
    - Producer practices: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/producers
    - Kafka Connect: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/connect
    - Replicaton considerations: consideration.md
  - Operations: 
    - Monitoring with Prometheus and Grafana: monitoring.md
    - Rolling upgrade: upgrade.md
  - Security: security.md
  - Tests: perf-tests.md
  - Compendium: compendium.md
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences