apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: mm2-l2e-cluster
  namespace: eda-strimzi-kafka24
spec:
  version: 2.4.0
  replicas: 1
  connectCluster: "kafka-on-premise-cluster-source"
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  clusters:
  - alias: "kafka-on-premise-cluster-source"
    bootstrapServers: eda-demo-24-cluster-kafka-bootstrap:9092
  - alias: "event-streams-wdc-target"
    bootstrapServers: broker-3-h6s2xk6b2t77g4p1.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-1-h6s2xk6b2t77g4p1.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-0-h6s2xk6b2t77g4p1.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-5-h6s2xk6b2t77g4p1.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-2-h6s2xk6b2t77g4p1.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-4-h6s2xk6b2t77g4p1.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093
    config:
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
    tls: {}
    authentication:
      passwordSecret:
          secretName: es-api-secretmgr  
          password: password 
      username: token
      type: plain
  mirrors:
  - sourceCluster: "kafka-on-premise-cluster-source"
    targetCluster: "event-streams-wdc-target"
    sourceConnector:
      config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
          heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
          checkpoints.topic.replication.factor: 1
    topicsPattern: "orders"
    groupsPattern: ".*"